<a href="https://colab.research.google.com/github/Anandukc/deep-learning-project/blob/main/d2_binnary_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# read file
import numpy as np
import pandas as pd
df=pd.read_csv('/content/bill_authentication.csv')
df

      Variance  Skewness  Curtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [4]:
#find missing values
df.isna().sum()

Variance    0
Skewness    0
Curtosis    0
Entropy     0
Class       0
dtype: int64

In [10]:
# type
df.dtypes

Variance    float64
Skewness    float64
Curtosis    float64
Entropy     float64
Class         int64
dtype: object

In [11]:
#separate x and y
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

x.head

<bound method NDFrame.head of       Variance  Skewness  Curtosis  Entropy
0      3.62160   8.66610   -2.8073 -0.44699
1      4.54590   8.16740   -2.4586 -1.46210
2      3.86600  -2.63830    1.9242  0.10645
3      3.45660   9.52280   -4.0112 -3.59440
4      0.32924  -4.45520    4.5718 -0.98880
...        ...       ...       ...      ...
1367   0.40614   1.34920   -1.4501 -0.55949
1368  -1.38870  -4.87730    6.4774  0.34179
1369  -3.75030 -13.45860   17.5932 -2.77710
1370  -3.56370  -8.38270   12.3930 -1.28230
1371  -2.54190  -0.65804    2.6842  1.19520

[1372 rows x 4 columns]>

In [13]:
# train data split
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

x_test

      Variance  Skewness   Curtosis  Entropy
1240   -3.5510   1.89550   0.186500 -2.44090
703     1.3114   4.54620   2.293500  0.22541
821    -4.0173  -8.31230  12.454700 -1.43750
1081   -5.1190   6.64860  -0.049987 -6.52060
37      3.6289   0.81322   1.627700  0.77627
...        ...       ...        ...      ...
559     2.0165  -0.25246   5.170700  1.07630
400     1.3049  -0.15521   6.491100 -0.75346
439     4.7285   2.10650  -0.283050  1.56250
634     6.8248   5.21870  -2.542500  0.54610
628     3.5251   0.72010   1.692800  0.64438

[412 rows x 4 columns]

In [14]:
x_train

      Variance  Skewness  Curtosis   Entropy
694    0.74054   0.36625  2.199200  0.484030
880   -2.35180  -4.83590  6.647900 -0.060358
1251  -0.77688   0.13036 -0.031137 -0.353890
812   -2.06590   1.05120 -0.462980 -1.097400
1212  -2.45600  -0.24418  1.404100 -0.458630
...        ...       ...       ...       ...
715    3.49160   8.57090 -3.032600 -0.591820
905    0.74521   3.63570 -4.404400 -4.141400
1096  -4.36670   6.06920  0.572080 -5.466800
235    2.04660   2.03000  2.176100 -0.083634
1061  -2.31470   3.66680 -0.696900 -1.247400

[960 rows x 4 columns]

In [16]:
#normalisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train)
x_train=sc.transform(x_train)
x_test=sc.transform(x_test)
x_train

array([[ 0.10527877, -0.27983064,  0.2259937 ,  0.78802844],
       [-0.99840564, -1.18889897,  1.31324557,  0.52830217],
       [-0.4363023 , -0.32105208, -0.31909545,  0.38825872],
       ...,
       [-1.71754187,  0.71675177, -0.17167062, -2.05109895],
       [ 0.57142352,  0.01090731,  0.22034811,  0.51719724],
       [-0.98516431,  0.29693578, -0.48180637, -0.03803285]])

In [18]:
# import libraries
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation

In [20]:
# create object
model=tf.keras.models.Sequential()

In [21]:
#input layer
model.add(Dense(4,activation='relu'))

In [22]:
# hidden layer
model.add(Dense(8,activation='relu'))

In [23]:
# output layer
model.add(Dense(1,activation='sigmoid'))

In [24]:
#weight update
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [25]:
# fit model
model.fit(x_train,y_train,batch_size=10,epochs=50)

Epoch 1/50
96/96 [==============================] - 1s 2ms/step - loss: 0.6771 - accuracy: 0.5635
Epoch 2/50
96/96 [==============================] - 0s 2ms/step - loss: 0.6021 - accuracy: 0.7469
Epoch 3/50
96/96 [==============================] - 0s 2ms/step - loss: 0.4824 - accuracy: 0.8875
Epoch 4/50
96/96 [==============================] - 0s 2ms/step - loss: 0.3166 - accuracy: 0.9615
Epoch 5/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1954 - accuracy: 0.9771
Epoch 6/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1285 - accuracy: 0.9844
Epoch 7/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0920 - accuracy: 0.9865
Epoch 8/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0702 - accuracy: 0.9896
Epoch 9/50
96/96 [==============================] - 0s 3ms/step - loss: 0.0559 - accuracy: 0.9885
Epoch 10/50
96/96 [==============================] - 0s 3ms/step - loss: 0.0461 - accuracy: 0.9896
Epoch 11/50
96/96 [==============================] - 0s 3ms/step - loss: 0.0390 - accuracy: 0.9937
Epoch 12/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0334 - accuracy: 0.9958
Epoch 13/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0291 - accuracy: 0.9958
Epoch 14/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0255 - accuracy: 0.9979
Epoch 15/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0227 - accuracy: 0.9990
Epoch 16/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0203 - accuracy: 0.9990
Epoch 17/50
96/96 [==============================] - 0s 3ms/step - loss: 0.0182 - accuracy: 0.9990
Epoch 18/50
96/96 [==============================] - 0s 3ms/step - loss: 0.0165 - accuracy: 0.9990
Epoch 19/50
96/96 [==============================] - 0s 3ms/step - loss: 0.0149 - accuracy: 0.9990
Epoch 20/50
96/96 [==============================] - 0s 3ms/step - loss: 0.0136 - accuracy: 0.9990
Epoch 21/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0124 - accuracy: 0.9990
Epoch 22/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0113 - accuracy: 0.9990
Epoch 23/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0103 - accuracy: 0.9990
Epoch 24/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0095 - accuracy: 0.9990
Epoch 25/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0087 - accuracy: 0.9990
Epoch 26/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0081 - accuracy: 0.9990
Epoch 27/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0075 - accuracy: 0.9990
Epoch 28/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0069 - accuracy: 0.9990
Epoch 29/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0064 - accuracy: 0.9990
Epoch 30/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0059 - accuracy: 0.9990
Epoch 31/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0055 - accuracy: 0.9990
Epoch 32/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0051 - accuracy: 0.9990
Epoch 33/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0047 - accuracy: 1.0000
Epoch 34/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0044 - accuracy: 1.0000
Epoch 35/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 36/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0039 - accuracy: 1.0000
Epoch 37/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0036 - accuracy: 1.0000
Epoch 38/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0033 - accuracy: 1.0000
Epoch 39/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0031 - accuracy: 1.0000
Epoch 40/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 41/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0027 - accuracy: 1.0000
Epoch 42/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0026 - accuracy: 1.0000
Epoch 43/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0024 - accuracy: 1.0000
Epoch 44/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0023 - accuracy: 1.0000
Epoch 45/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0021 - accuracy: 1.0000
Epoch 46/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0019 - accuracy: 1.0000
Epoch 47/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0018 - accuracy: 1.0000
Epoch 48/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000
Epoch 49/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 50/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 1.0000

In [27]:
# performance evaluation
loss,accu=model.evaluate(x_test,y_test)
print("Accuracy:",accu)
print("Loss:",loss)

13/13 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 1.0000
Accuracy: 1.0
Loss: 0.00320727308280766

In [28]:
import warnings
warnings.filterwarnings('ignore')

In [31]:
new_pred=model.predict(sc.transform([[0.32924,-4.45520,4.5712,-0.98880]]))
if new_pred>0.5:
  print("Yes/1")
else:
  print("No/0")

1/1 [==============================] - 0s 23ms/step
No/0